### ISSUE TITLE
Horizontal scroll always visible

### ISSUE THREAD

**Issue by VMBindraban** [DBuit/hass-smart-home-panel-card#7]
Is there a reason why the horizontal scroll is always visible?

```css
.page > .main {
    width: 70%;
    overflow-x: scroll;
}
```

<img width="956" alt="Untitled" src="https://user-images.githubusercontent.com/2269400/105578201-b6426880-5d7e-11eb-857d-5196bfaed0a8.png">
